// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RT_Inventory.Api.Data;

#nullable disable

namespace RT_Inventory.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.AsnGrn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AsnGrnNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ChallanCopyPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallanNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ItemYarnType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PoNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TotalBagQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsterReportPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WeightPerBag")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("AsnGrnNo")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("AsnGrns");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.IssueSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PickingListId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PickingListId");

                    b.HasIndex("StartedByUserId");

                    b.ToTable("IssueSessions");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.MrrApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("AsnGrnId")
                        .HasColumnType("int");

                    b.Property<string>("MrrNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("AsnGrnId")
                        .IsUnique();

                    b.HasIndex("MrrNo")
                        .IsUnique();

                    b.ToTable("MrrApprovals");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.PickingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("PickingListNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("RequisitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeValue")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PickingListNo")
                        .IsUnique();

                    b.HasIndex("RequisitionId");

                    b.ToTable("PickingLists");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.ReceiveSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsnGrnId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsnGrnId");

                    b.HasIndex("StartedByUserId");

                    b.ToTable("ReceiveSessions");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.Requisition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("RequisitionNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RequisitionNo")
                        .IsUnique();

                    b.ToTable("Requisitions");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.RequisitionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemYarnType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LotNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("RequiredBagQty")
                        .HasColumnType("int");

                    b.Property<decimal>("RequiredWeight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("RequisitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionItems");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.ReturnRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnAsnGrnId")
                        .HasColumnType("int");

                    b.Property<string>("ReturnNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("SourceRequisitionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ReturnAsnGrnId");

                    b.HasIndex("ReturnNo")
                        .IsUnique();

                    b.HasIndex("SourceRequisitionId");

                    b.ToTable("ReturnRequests");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.RfidTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsnGrnId")
                        .HasColumnType("int");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("int");

                    b.Property<int?>("BagNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TagValue")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AsnGrnId");

                    b.HasIndex("TagValue", "IsActive")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("RfidTags");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.RfidTagHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RfidTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("RfidTagId");

                    b.ToTable("RfidTagHistories");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsnGrnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemYarnType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("RfidTagId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("AsnGrnId");

                    b.HasIndex("RfidTagId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsnGrnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<int?>("RequisitionId")
                        .HasColumnType("int");

                    b.Property<int>("RfidTagId")
                        .HasColumnType("int");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("AsnGrnId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RequisitionId");

                    b.HasIndex("RfidTagId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.WarningLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsnGrnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IssueSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReceiveSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("RequisitionId")
                        .HasColumnType("int");

                    b.Property<string>("RfidTagValue")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("WarningType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsnGrnId");

                    b.HasIndex("IssueSessionId");

                    b.HasIndex("ReceiveSessionId");

                    b.HasIndex("RequisitionId");

                    b.ToTable("WarningLogs");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.AsnGrn", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.IssueSession", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.PickingList", "PickingList")
                        .WithMany("IssueSessions")
                        .HasForeignKey("PickingListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "StartedByUser")
                        .WithMany()
                        .HasForeignKey("StartedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickingList");

                    b.Navigation("StartedByUser");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.MrrApproval", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RT_Inventory.Api.Models.Entities.AsnGrn", "AsnGrn")
                        .WithOne("MrrApproval")
                        .HasForeignKey("RT_Inventory.Api.Models.Entities.MrrApproval", "AsnGrnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("AsnGrn");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.PickingList", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RT_Inventory.Api.Models.Entities.Requisition", "Requisition")
                        .WithMany("PickingLists")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.ReceiveSession", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.AsnGrn", "AsnGrn")
                        .WithMany("ReceiveSessions")
                        .HasForeignKey("AsnGrnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "StartedByUser")
                        .WithMany()
                        .HasForeignKey("StartedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsnGrn");

                    b.Navigation("StartedByUser");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.Requisition", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.RequisitionItem", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.Requisition", "Requisition")
                        .WithMany("Items")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.ReturnRequest", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RT_Inventory.Api.Models.Entities.AsnGrn", "ReturnAsnGrn")
                        .WithMany()
                        .HasForeignKey("ReturnAsnGrnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RT_Inventory.Api.Models.Entities.Requisition", "SourceRequisition")
                        .WithMany()
                        .HasForeignKey("SourceRequisitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("ReturnAsnGrn");

                    b.Navigation("SourceRequisition");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.RfidTag", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.AsnGrn", "AsnGrn")
                        .WithMany("RfidTags")
                        .HasForeignKey("AsnGrnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AsnGrn");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.RfidTagHistory", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RT_Inventory.Api.Models.Entities.RfidTag", "RfidTag")
                        .WithMany("Histories")
                        .HasForeignKey("RfidTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("RfidTag");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.Stock", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.AsnGrn", "AsnGrn")
                        .WithMany("Stocks")
                        .HasForeignKey("AsnGrnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RT_Inventory.Api.Models.Entities.RfidTag", "RfidTag")
                        .WithMany("Stocks")
                        .HasForeignKey("RfidTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsnGrn");

                    b.Navigation("RfidTag");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.StockTransaction", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.AsnGrn", "AsnGrn")
                        .WithMany()
                        .HasForeignKey("AsnGrnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RT_Inventory.Api.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RT_Inventory.Api.Models.Entities.Requisition", "Requisition")
                        .WithMany()
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RT_Inventory.Api.Models.Entities.RfidTag", "RfidTag")
                        .WithMany("StockTransactions")
                        .HasForeignKey("RfidTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsnGrn");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Requisition");

                    b.Navigation("RfidTag");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.User", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.WarningLog", b =>
                {
                    b.HasOne("RT_Inventory.Api.Models.Entities.AsnGrn", "AsnGrn")
                        .WithMany()
                        .HasForeignKey("AsnGrnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RT_Inventory.Api.Models.Entities.IssueSession", "IssueSession")
                        .WithMany("WarningLogs")
                        .HasForeignKey("IssueSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RT_Inventory.Api.Models.Entities.ReceiveSession", "ReceiveSession")
                        .WithMany("WarningLogs")
                        .HasForeignKey("ReceiveSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RT_Inventory.Api.Models.Entities.Requisition", "Requisition")
                        .WithMany()
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AsnGrn");

                    b.Navigation("IssueSession");

                    b.Navigation("ReceiveSession");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.AsnGrn", b =>
                {
                    b.Navigation("MrrApproval");

                    b.Navigation("ReceiveSessions");

                    b.Navigation("RfidTags");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.IssueSession", b =>
                {
                    b.Navigation("WarningLogs");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.PickingList", b =>
                {
                    b.Navigation("IssueSessions");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.ReceiveSession", b =>
                {
                    b.Navigation("WarningLogs");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.Requisition", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PickingLists");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.RfidTag", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("StockTransactions");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("RT_Inventory.Api.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
